version: "3.9"
services:
  editor:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:0-16-bullseye
    volumes:
      - ../:/app
      - ./.bashrc:/home/node/.bashrc
    working_dir: /app
    command: tail -f /dev/null

  postgres:
    image: postgres:latest
    container_name: nutrinova-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nutrinovadb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Pleasegivemecoke!
    volumes:
      - ../nutrinova-db/data:/var/lib/postgresql/data
      - ../nutrinova-db/init-scripts:/docker-entrypoint-initdb.d
    
