version: "3.9"
services:
  editor:
    build: .
    user: developer
    container_name: nutrinova-editor
    volumes:
      - developer_home:/home/developer
      - ../:/app
      - ./.bashrc:/home/developer/.bashrc
      - $HOME/.ssh:/home/developer/.ssh
    working_dir: /app
    command: tail -f /dev/null

  client:
    container_name: nutrinova-client
    build: 
      context: .
    user: developer
    volumes:
      - ../:/app
    command: >
      sh -c "
        cd nutrinova-ui
        npm i
        npm run dev
      "
    ports:
      - 3000:3000

  postgres:
    image: postgres:latest
    container_name: nutrinova-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nutrinovadb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Pleasegivemecoke!
    volumes:
      - ../nutrinova-db/data:/var/lib/postgresql/data
      - ../nutrinova-db/init-scripts:/docker-entrypoint-initdb.d
    
volumes:
  developer_home: