version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: nutrinova-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nutrinovadb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Pleasegivemecoke!
      PUID: 1000
      PGID: 1000
    volumes:
      - ../home/caleb/nutrinovadata/data:/var/lib/postgresql/data
      - ../nutrinova-db/init-scripts:/docker-entrypoint-initdb.d

  client:
    container_name: nutrinova-client
    build: 
      context: ../nutrinova-ui/

  api:
    container_name: nutrinova_api
    build: 
      context: ../nutrinova-api/

  swag:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=nutrinova.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/caleb/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
    - 0.0.0.0:1359:443
    restart: unless-stopped