version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: nutrinova-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /home/caleb/nutrinovadata/data:/var/lib/postgresql/data
      - ../nutrinova-db/init-scripts:/docker-entrypoint-initdb.d

  client:
    container_name: nutrinova-client
    build:
      context: ../nutrinova-ui/
      args:
        - NUTRINOVA_API_URL=${NUTRINOVA_API_URL}
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}

  api:
    container_name: nutrinova-api
    build:
      context: ../nutrinova-api/
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - USDA_API_KEY=${USDA_API_KEY}

  swag:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=nutrinova.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/caleb/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 0.0.0.0:1359:443
    restart: unless-stopped
