version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: nutrinova-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /home/nutrinova/nutrinovadata/data:/var/lib/postgresql/data
      - ../nutrinova-db/init-scripts:/docker-entrypoint-initdb.d
    restart: always

  client:
    container_name: nutrinova-client
    build:
      context: ../nutrinova-ui/
      args:
        - NUTRINOVA_API_URL=${NUTRINOVA_API_URL}
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - WEBSOCKET_URL=${WEBSOCKET_URL}
    restart: always

  api:
    container_name: nutrinova-api
    user: 0:0
    build:
      context: ../nutrinova-api/
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - USDA_API_KEY=${USDA_API_KEY}
      - OpenAIServiceOptions__ApiKey=${OPENAI_API_KEY}
    restart: always
    # This might not be needed but this is how I did file permissions for the ChatApp
    # If there is a better way to do this please let me know
    entrypoint:
      - /bin/bash
      - -c
      - |
        chown -R 1000:1000 /app/images
        su nutrinova 
        dotnet NutrinovaApi.dll
    volumes:
      - /home/nutrinova:/app/images

  swag:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=nutrinova.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/nutrinova/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 0.0.0.0:1359:443
    restart: unless-stopped
