name: Dotnet Api Integrations Tests

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: [ self-hosted ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies and run tests
      run: |
        cd nutrinova-api/NutrinovaApi.IntegrationTests
        dotnet restore
        dotnet test