name: Dotnet Api Integrations Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies and run tests
        run: |
          cd nutrinova-api/
          docker build -t api_integration_tests -f test.Dockerfile .
          docker run -i --rm -v /var/run/docker.sock.raw:/var/run/docker.sock api_integration_tests
