name: Build front and back 

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  build-backend:
    runs-on: [ self-hosted ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies and build 
      run: |
        cd nutrinova-api/NutrinovaApi
        dotnet restore
        dotnet build
  
  build-frontend:
    runs-on: [ self-hosted ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup node 
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build 
      run: |
        cd nutrinova-ui
        npm i
        npm run build