name: Build front and back

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-backend:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Backend
        run: |
          cd nutrinova-api/
          docker build -t nutrinova_api_build -f build.Dockerfile .
          docker run -i --rm nutrinova_api_build

  build-frontend:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Frontend
        run: |
          cd nutrinova-ui/
          docker build -t nutrinova_ui_build -f build.Dockerfile .
          docker run -i --rm nutrinova_ui_build
