name: Deploy To Production

env:
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
  KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
  KEYCLOAK_BASE_URL: ${{ secrets.KEYCLOAK_BASE_URL }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  NUTRINOVA_API_URL: ${{ secrets.NUTRINOVA_API_URL }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  USDA_API_KEY: ${{ secrets.USDA_API_KEY }}
  WEBSOCKET_URL: ${{ secrets.WEBSOCKET_URL }}
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-ui:
    uses: ./.github/workflows/ui_lint.yml

  test-api:
    needs: lint-ui
    uses: ./.github/workflows/api_integration_tests.yml

  deploy-application:
    needs: test-api
    runs-on: [self-hosted]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: redeploy application
        run: |
          cd ops
          docker compose pull
          docker compose build --no-cache
          docker compose up -d
