name: deploy
env: 
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
on: 
  push: 
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
jobs:
  deploy-application:
    runs-on: [ self-hosted ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: redeploy application
        run: |
          cd ops
          docker compose pull
          docker compose build
          docker compose up -d