name: Deploy To Production
env: 
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
on: 
  workflow_dispatch:
    branches:
      - main
jobs:
  test-api:
    runs-on: [ self-hosted ]
    uses: ./.github/workflows/api_integration_tests.yml

  deploy-application:
    needs: test-api
    runs-on: [ self-hosted ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: redeploy application
        run: |
          cd ops
          docker compose pull
          docker compose build
          docker compose up -d
