name: deploy
env: 
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
on: 
  workflow_dispatch:
    branches:
      - main
jobs:
  test-api:
    runs-on: [ self-hosted ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Test Dotnet Api 
      uses: ./.github/actions/testapi

  deploy-application:
    needs: test-api
    runs-on: [ self-hosted ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: redeploy application
        run: |
          cd ops
          docker compose pull
          docker compose build
          docker compose up -d
