name: Deploy To Production

env:
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-ui:
    uses: ./.github/workflows/ui_lint.yml

  test-api:
    uses: ./.github/workflows/api_integration_tests.yml

  deploy-application:
    needs: test-api
    runs-on: [self-hosted]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: redeploy application
        run: |
          cd ops
          docker compose pull
          docker compose build
          docker compose up -d
