name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
jobs:
  check-lint:
    uses: ./.github/workflows/ui_lint.yml

  check-tests:
    needs: check-lint
    uses: ./.github/workflows/api_integration_tests.yml

  check-projects-build:
    needs: check-tests
    uses: ./.github/workflows/build.yml
