name: Pull Request Checks 

on: 
  pull_request:
    branches:
      - main

jobs:
  check-lint:
    uses: ./.github/workflows/ui_lint.yml

  check-tests:
    uses: ./.github/workflows/api_integration_tests.yml
  
  check-projects-build:
    uses: ./.github/workflows/build.yml
