name: Run Integration Tests

on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [ self-hosted ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'  # Adjust the version to match your project's .NET SDK version.

    - name: Restore dependencies and run tests
      run: |
        cd nutrinova-api/NutrinovaApi-IntegrationTests
        dotnet restore
        dotnet test