name: Lint Next.js Project

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint-frontend:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Frontend
        run: |
          cd nutrinova-ui/
          docker build -t nutrinova_ui_lint -f lint.Dockerfile .
          docker run -i --rm nutrinova_ui_lint
